import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1E1E2F',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFD700',
    textAlign: 'center',
    marginBottom: 20,
  },
  otherText: {
    fontSize: 28,
    fontWeight: '700',
    color: '#067bc9ff',
    textAlign: 'center',
    marginBottom: 20,
  },
  item: {
    fontSize: 18,
    padding: 15,
    marginVertical: 8,
    backgroundColor: '#4B0082',
    borderRadius: 14,
    textAlign: 'center',
    color: '#FFD700',
    fontWeight: '700',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  mealItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#00CED1',
    marginVertical: 8,
    padding: 12,
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  mealImage: {
    width: 80,
    height: 80,
    borderRadius: 14,
    marginRight: 15,
    borderWidth: 2,
    borderColor: '#FF6347',
  },
  mealName: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1E1E2F',
  },
  recipeCard: {
    marginBottom: 24,
    padding: 18,
    backgroundColor: '#2E0854',
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  recipeTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFD700',
    marginBottom: 16,
    textAlign: 'center',
  },
  recipeImage: {
    width: '100%',
    height: 240,
    borderRadius: 16,
    marginBottom: 15,
    borderWidth: 3,
    borderColor: '#FF6347',
  },
  recipeText: {
    fontSize: 16,
    color: '#E5E5E5',
    marginBottom: 10,
    lineHeight: 22,
    fontWeight: '500',
  },
});
